# 载入数据

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#from mpl_toolkits.basemap import Basemap
%matplotlib inline
sns.set(style="white", context="talk")

starbucks = pd.read_csv('directory.csv')

In [9]:
starbucks.head()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
0,Starbucks,47370-257954,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD,AD500,376818720,GMT+1:00 Europe/Andorra,1.53,42.51
1,Starbucks,22331-212325,Ajman Drive Thru,Licensed,"1 Street 69, Al Jarf",Ajman,AJ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,55.47,25.42
2,Starbucks,47089-256771,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,55.47,25.39
3,Starbucks,22126-218024,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.38,24.48
4,Starbucks,17127-178586,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.54,24.51

# 门店数量最多国家TOP10

中国排第2

In [11]:
starbucks.Country.value_counts()[:10]

US    13608
CN     2734
CA     1468
JP     1237
KR      993
GB      901
MX      579
TW      394
TR      326
PH      298
Name: Country, dtype: int64

中国门店数量最多的城市TOP10

In [60]:
cn_starbucks = starbucks[starbucks.Country == 'CN']
cn_city = cn_starbucks['State/Province'].value_counts()
cn_city

31    551
32    354
44    333
33    315
11    236
91    162
51    104
42     76
35     75
37     75
12     58
21     57
61     42
50     41
43     35
34     26
53     24
13     24
41     21
45     21
46     16
23     16
36     13
92     13
22     13
52      9
15      8
14      8
63      3
62      3
64      2
Name: State/Province, dtype: int64

In [49]:
cn_starbucks.ix[3061,'City'] = '上海市'

C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\indexing.py:477: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [56]:
cn_starbucks[cn_starbucks.City == 'shanghai'] = '上海市'

Empty DataFrame
Columns: [Brand, Store Number, Store Name, Ownership Type, Street Address, City, State/Province, Country, Postcode, Phone Number, Timezone, Longitude, Latitude]
Index: []

In [68]:
cn_starbucks['Ownership Type'].value_counts()

Company Owned    1339
Joint Venture    1220
Licensed          175
Name: Ownership Type, dtype: int64

In [73]:
cn_starbucks.Brand.groupby([cn_starbucks['City'],cn_starbucks['Ownership Type']]).count().unstack()

Ownership Type   Company Owned  Joint Venture  Licensed
City
Admiralty                  NaN            NaN       2.0
Causeway Bay               NaN            NaN       5.0
Central                    NaN            NaN       1.0
Chaiwan                    NaN            NaN       1.0
Changshu                   NaN            1.0       NaN
Changzhou                  NaN            1.0       NaN
Fortress Hill              NaN            NaN       1.0
Hangzhou                   NaN            2.0       NaN
Hong Kong                  NaN            NaN     104.0
Jiaxing                    NaN            2.0       NaN
Jinhua                     NaN            1.0       NaN
Kowloon                    NaN            NaN      19.0
Kowloon Bay                NaN            NaN       1.0
Kowloon Tong               NaN            NaN       1.0
Lantau Island              NaN            NaN       2.0
Macau                      NaN            NaN      13.0
Mong Kok                   NaN            NaN       2.0
N.T.                       NaN            NaN       2.0
Nanjing                    NaN            1.0       NaN
Nantong                    NaN            4.0       NaN
New Territories            NaN            NaN       7.0
Ningbo                     NaN            3.0       NaN
Quarry Bay                 NaN            NaN       3.0
ShangHai                   NaN            2.0       NaN
Shanghai                   NaN            2.0       NaN
Shantin                    NaN            NaN       1.0
Stanley                    NaN            NaN       1.0
Suzhou                     NaN            3.0       NaN
Tai Koo Shing              NaN            NaN       1.0
Tin Hau                    NaN            NaN       1.0
...                        ...            ...       ...
萧山市                        NaN            1.0       NaN
蚌埠市                        1.0            NaN       NaN
衡阳市                        3.0            NaN       NaN
衢州市                        NaN            3.0       NaN
襄樊市                        1.0            NaN       NaN
襄阳市                        2.0            NaN       NaN
西宁市                        3.0            NaN       NaN
西安市                       40.0            NaN       NaN
诸暨市                        NaN            2.0       NaN
贵阳                         8.0            NaN       NaN
贵阳市                        1.0            NaN       NaN
连云港                        NaN            1.0       NaN
连云港市                       NaN            3.0       NaN
邢台市                        1.0            NaN       NaN
邯郸                         1.0            NaN       NaN
郑州市                       18.0            NaN       NaN
重庆市                       41.0            NaN       NaN
金华市                        NaN           11.0       NaN
银川市                        2.0            NaN       NaN
镇江市                        NaN            9.0       NaN
长春市                       10.0            NaN       NaN
长沙市                       26.0            NaN       NaN
阳江市                        1.0            NaN       NaN
青岛市                       28.0            NaN       NaN
靖江市                        NaN            2.0       NaN
鞍山市                        3.0            NaN       NaN
马鞍山                        3.0            NaN       NaN
高邮市                        NaN            1.0       NaN
黄石市                        1.0            NaN       NaN
龙岩市                        2.0            NaN       NaN

[197 rows x 3 columns]